server:
  port: 8082

  #our employee service should connect to our service registry of:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employee

    username: postgres
    password: Password

  jpa:
    hibernate:
      ddl-auto: create-drop



